conda_build_tool: rattler-build
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
build_platform:
  osx_arm64: osx_64
github_actions:
  self_hosted: true
  timeout_minutes: 1200
  triggers:
    - push
    - pull_request
provider:
  linux_64: github_actions
test: native_and_emulated
